version: '3.2'

services:

  backend:
    image: php:7.2-apache
    volumes:
      - ./extra/backend.php:/var/www/html/index.php
    networks:
      - sporadicator-network

  sporadicator:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/sporadicator
    networks:
      - sporadicator-network
    command: "mvn spring-boot:run"
    user: "1000:1000"
    ports:
      - 8080:8080
      - 8181:8181
      - 8282:8282
      - 5005:5005

networks:
  sporadicator-network:

